version: '3'

services:
  app:
    build: .
    volumes:
      - ./:/code
    ports:
      - 5000:5000
      - 8080:8080
    depends_on:
      - mongodb
  mongodb:
    image: mongo:jessie
    volumes:
      - /Users/eezhal/mongo-volumne:/data/db
    ports:
      - 27018:27017